version: '3.1'

services:
  database:
    image: mysql:5.7.20
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: demo
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: service01
      MYSQL_PASSWORD: pass

  userservice:
    image: user-service:1.0
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      DATABASESERVER_PORT: "3306"